// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2cue

// ArrayJob defines all methods which can be executed on a
// DRMAA2 job array. A job array contains a set of jobs with
// the same properties (same job template).
#ArrayJob: _
