// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2cue

_#_Capability_name: "AdvanceReservationReserveSlotsCallbackBulkJobsMaxParallelJtEmailJtStagingJtDeadlineJtMaxSlotsJtAccountingIDRtStartNowRtDurationRtMachineOSRtMachineArch"
