// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package drmaa2interface

import "fmt"

const _Capability_name = "AdvanceReservationReserveSlotsCallbackBulkJobsMaxParallelJtEmailJtStagingJtDeadlineJtMaxSlotsJtAccountingIDRtStartNowRtDurationRtMachineOSRtMachineArch"

var _Capability_index = [...]uint8{0, 18, 30, 38, 57, 64, 73, 83, 93, 107, 117, 127, 138, 151}

func (i Capability) String() string {
	if i < 0 || i >= Capability(len(_Capability_index)-1) {
		return fmt.Sprintf("Capability(%d)", i)
	}
	return _Capability_name[_Capability_index[i]:_Capability_index[i+1]]
}

func CapabilityFromString(cap string) (Capability, bool) {
	switch cap {
	case "AdvanceReservation":
		return AdvanceReservation, true
	case "ReserveSlots":
		return ReserveSlots, true
	case "Callback":
		return Callback, true
	case "BulkJobsMaxParallel":
		return BulkJobsMaxParallel, true
	case "JtEmail":
		return JtEmail, true
	case "JtStaging":
		return JtStaging, true
	case "JtDeadline":
		return JtDeadline, true
	case "JtMaxSlots":
		return JtMaxSlots, true
	case "JtAccountingID":
		return JtAccountingID, true
	case "RtStartNow":
		return RtStartNow, true
	case "RtDuration":
		return RtDuration, true
	case "RtMachineOS":
		return RtMachineOS, true
	case "RtMachineArch":
		return RtMachineArch, true
	default:
		return AdvanceReservation, false
	}
}