// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2interface

_#_CPU_name: "OtherCPUAlphaARMARM64CellPARISCPARISC64x86x64IA64MIPSMIPS64PowerPCPowerPC64SPARCSPARC64"
