// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2interface

_#_ErrorID_name: "SuccessDeniedByDrmsDrmCommunicationTryLaterSessionManagementTimeoutInternalInvalidArgumentInvalidSessionInvalidStateOutOfResourceUnsupportedAttributeUnsupportedOperationImplementationSpecificLastError"
