// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2interface

// JobSession contains all functions for managing jobs within
// one names job session. Multiple concurrent job sessions can
// be used at one point in time. A job session is a logical
// concept for separating workflows.
#JobSession: _
