// Code generated by "stringer -type=JobState"; DO NOT EDIT.

package drmaa2interface

import "fmt"

const _JobState_name = "UnsetUndeterminedQueuedQueuedHeldRunningSuspendedRequeuedRequeuedHeldDoneFailed"

var _JobState_index = [...]uint8{0, 5, 17, 23, 33, 40, 49, 57, 69, 73, 79}

func (i JobState) String() string {
	if i < 0 || i >= JobState(len(_JobState_index)-1) {
		return fmt.Sprintf("JobState(%d)", i)
	}
	return _JobState_name[_JobState_index[i]:_JobState_index[i+1]]
}

func JobStateFromString(state string) (JobState, bool) {
	switch state {
	case "Unset":
		return Unset, true
	case "Undetermined":
		return Undetermined, true
	case "Queued":
		return Queued, true
	case "QueuedHeld":
		return QueuedHeld, true
	case "Running":
		return Running, true
	case "Suspended":
		return Suspended, true
	case "Requeued":
		return Requeued, true
	case "RequeuedHeld":
		return RequeuedHeld, true
	case "Done":
		return Done, true
	case "Failed":
		return Failed, true
	default:
		return Unset, false
	}
}