// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2cue

// MonitoringSession interface defines all methods required for
// implementing a DRMAA2 compatible monitoring session.
#MonitoringSession: _
