// Code generated by "stringer -type=OS"; DO NOT EDIT.

package drmaa2interface

import "fmt"

const _OS_name = "OtherOSAIXBSDLinuxHPUXIRIXMacOSSunOSTRU64UnixWareWinWinNT"

var _OS_index = [...]uint8{0, 7, 10, 13, 18, 22, 26, 31, 36, 41, 49, 52, 57}

func (i OS) String() string {
	if i < 0 || i >= OS(len(_OS_index)-1) {
		return fmt.Sprintf("OS(%d)", i)
	}
	return _OS_name[_OS_index[i]:_OS_index[i+1]]
}

func OSFromString(os string) (OS, bool) {
	switch os {
	case "OtherOS":
		return OtherOS, true
	case "AIX":
		return AIX, true
	case "BSD":
		return BSD, true
	case "Linux":
		return Linux, true
	case "HPUX":
		return HPUX, true
	case "IRIX":
		return IRIX, true
	case "MacOS":
		return MacOS, true
	case "SunOS":
		return SunOS, true
	case "TRU64":
		return TRU64, true
	case "UnixWare":
		return UnixWare, true
	case "Win":
		return Win, true
	case "WinNT":
		return WinNT, true
	default:
		return OtherOS, false
	}
}
