// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2interface

// Queue implements all required elements of a queue.
#Queue: {
	Extensible: #Extensible
	Name:       string @xml(name)
}
