// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/dgruber/drmaa2interface

package drmaa2interface

// Version is a DRMAA2 version type which holds the major version
// and minor version.
#Version: {
	Major: string
	Minor: string
}
